spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/reactive_order_monitor
    username: reactive
    password: qwerty
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8081